easy_admin:
    site_name: ADMIN 1.0 # insert html <balise> for logo

    # Configuration for all list and show views
    list:
        title: 'list.%%entity_label%%'
        max_results: 5
    show:
        title: '%%entity_label%% (#%%entity_id%%)'

    entities:
        # List the entity class name you want to manage
        Post:
            class: App\Entity\Post
            label: Post

            list:
#                fields: ['id']
                help: "Message"

            show:
                title: '%%entity_label%% (#%%entity_id%%)'

            new:
                help: "Message ICI"
                fields:
                    - 'title'
                    - { property: 'content', type: 'textarea' }
                    - 'draft'
#                    - { property: 'categories', type: 'easyadmin_autocomplete' }
                    - { property: 'categories', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Category' } }
            edit:
                fields:
                    - 'title'
                    - 'content'
                    - 'draft'

        Category:
            class: App\Entity\Category
            label: Category
            list:
                title: 'list.%%entity_label%%'
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
            form:
               fields:
                   - 'name'
                   - 'draft'

        User:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastlogin
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }



    design:
        brand_color: #40A497

